version: '3'

services:
  mysql:
    build: .
    container_name: mysql-server
    ports:
      - "4000:3306"
    env_from:
      - var.env
    environment:
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD

